<?php
echo "<!DOCTYPE html>\n";
echo "html>\n";
echo "head>\n";
echo "<meta charset=\"utf-8\">\n";
echo "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n";
echo "   <meta http-equiv=\"content-type\" content=\"text/html; charset=utf-8\">\n";
echo "   <meta name=\"viewport\" content=\"width=device-width,initial-scale=1,maximum-scale=1,user-scalable=no\">\n";
echo "     <title>TDOBP</title>\n";
echo "    <link rel=\"shortcut icon\" href=\"logo1.png\" style=\"height: 40px;width: 40px;\">\n";
echo "    <link rel=\"stylesheet\" type=\"text/css\" href=\"style.css\">\n";
echo " <link href=\"https://cdn.staticfile.org/twitter-bootstrap/5.1.1/css/bootstrap.min.css\" rel=\"stylesheet\">\n";
echo " <script src=\"https://cdn.staticfile.org/twitter-bootstrap/5.1.1/js/bootstrap.bundle.min.js\"></script>\n";
echo " <style>\n";
echo " /* Make the image fully responsive */\n";
echo " .carousel-inner img {\n";
echo "     width: 100%;\n";
echo "     height: 100%;\n";
echo " }\n";
echo " </style>\n";
echo " <style>\n";
echo "body {\n";
echo "background-color: #E6E6FA;\n";
echo "overflow: scroll;\n";
echo "/style>\n";
echo "style type=\"text/css\">\n";
echo ":selection {\n";
echo "   color:#fff;\n";
echo "   background-color: #5CB85C ;\n";
echo "\n";
echo "::-moz-selection {\n";
echo "   color:#fff;\n";
echo "   background-color: #5CB85C ;\n";
echo "\n";
echo "::-webkit-selection {\n";
echo "   color:#fff;\n";
echo "   background-color: #5CB85C ;\n";
echo "\n";
echo "</style>\n";
echo "/head>\n";
echo "body>\n";
echo "nav class=\"navbar navbar-expand-md bg-dark navbar-dark\">\n";
echo " <div class=\"container-fluid\">\n";
echo "<a class=\"navbar-brand\" href=\"https://www.tdobp.eu.org/\">TDOBP <span class=\"badge bg-secondary\">MY</span></a>\n";
echo "   <button class=\"navbar-toggler\" type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#collapsibleNavbar\">\n";
echo "     <span class=\"navbar-toggler-icon\"></span>\n";
echo "   </button>\n";
echo "   <!-- Navbar links -->\n";
echo " <div class=\"collapse navbar-collapse\" id=\"collapsibleNavbar\">\n";
echo "   <ul class=\"navbar-nav\">\n";
echo "     <li class=\"nav-item\">\n";
echo "       <a class=\"nav-link\" href=\"https://www.tdobp.eu.org/\">主页</a>\n";
echo "     </li>\n";
echo "     <li class=\"nav-item\">\n";
echo "       <a class=\"nav-link\" href=\"https://www.tdobp.eu.org/update\">日志</a>\n";
echo "     </li>  \n";
echo "   </ul>\n";
echo " </div>  \n";
echo " </div>\n";
echo "/nav>\n";
echo "!-- 轮播 -->\n";
echo "div id=\"demo\" class=\"carousel slide\" data-bs-ride=\"carousel\">\n";
echo "   <!-- 指示符 -->\n";
echo " <div class=\"carousel-indicators\">\n";
echo "   <button type=\"button\" data-bs-target=\"#demo\" data-bs-slide-to=\"0\" class=\"active\"></button>\n";
echo " </div>\n";
echo " \n";
echo " <!-- 轮播图片 -->\n";
echo " <div class=\"carousel-inner\">\n";
echo "   <div class=\"carousel-item active\">\n";
echo "     <img src=\"https://w.wallhaven.cc/full/6o/wallhaven-6oxgp6.jpg\" class=\"d-block\" style=\"width:%;height: px;\">\n";
echo "   </div>\n";
echo " </div>\n";
echo " \n";
echo " <!-- 左右切换按钮 -->\n";
echo " <button class=\"carousel-control-prev\" type=\"button\" data-bs-target=\"#demo\" data-bs-slide=\"prev\">\n";
echo "   <span class=\"carousel-control-prev-icon\"></span>\n";
echo " </button>\n";
echo " <button class=\"carousel-control-next\" type=\"button\" data-bs-target=\"#demo\" data-bs-slide=\"next\">\n";
echo "   <span class=\"carousel-control-next-icon\"></span>\n";
echo " </button>\n";
echo "/div>\n";
echo "\n";
echo " <br>\n";
echo " <div class=\"container p-5 my-5 bg-primary text-white\" align=\"center\">\n";
echo " <h1>TDOBP - 资讯 / 活动</h1>\n";
echo " <p>资讯将会不定时更新，请记得留守TDOBP参与最新活动！</p>\n";
echo "/div>\n";
echo "<div class=\"panel panel-default\" align=\"center\">\n";
echo "<div class=\"panel-body\">\n";
echo "\n";
echo "div align=\"center\">\n";
echo " 	\n";
echo "<div class=\"container mt-3\" align=\"center\">\n";
echo " <div class=\"card\">\n";
echo "   <div class=\"card-body\">\n";
echo "     <img src=\"pin.png\" class=\"media-object\" style=\"height: 50px; width: 50px;\">\n";
echo "     <h3 class=\"card-title\">News网页相关事宜 | TDOBP</h3><br>\n";
echo "     <h4 class=\"card-text\">此文件关于“News网页相关事宜”，请点击以下链接查看详细内容！\n";
echo "     </h4><br>\n";
echo "       <a href=\"https://www.tdobp.eu.org/2023%E5%B9%B44%E6%9C%8813%E6%97%A5.pdf\" target=\"_blank\" class=\"btn btn-primary\">查看详情</a>\n";
echo "   </div>\n";
echo " </div>\n";
echo "/div>\n";
echo "    </div>\n";
echo "/div>\n";
echo "/div>\n";
echo "</div>\n";
echo "/div>\n";
echo "<br>\n";
echo "br><br><br><br><br><br>\n";
echo "footer>\n";
echo "     <p align=\"center\">Copyright &copy;  All rights reserved  |  TDOBP</p>\n";
echo "     <p align=\"center\">Gmail : <a href=\"/cdn-cgi/l/email-protection\" class=\"__cf_email__\" data-cfemail=\"c3b7a7aca1b3eda6b6edacb1a483a4aea2aaafeda0acae\">[email&#160;protected]</a></p>\n";
echo "     <p align=\"center\">社交媒体 :&#12288<a href=\"https://discord.com/invite/kSdQSAFQ7F\" target=\"_blank\">\n";
echo " <img alt=\"\" src=\"Dlogo.png\" style=\"height: 30px; width: 30px;\" />\n";
echo "/a> &#12288<a href=\"https://tdobp.blogspot.com/\" target=\"_blank\">\n";
echo " <img alt=\"\" src=\"blog.png\" style=\"height: 30px; width: 30px;\" />\n";
echo "/a>&#12288<a href=\"https://docs.google.com/forms/d/e/1FAIpQLSenOwvY6K_w3kxn8npCx7H2XyW5xFd4D58qwanqGoHrHT0HKg/viewform?usp=sf_link\" target=\"_blank\">\n";
echo " <img alt=\"\" src=\"file.png\" style=\"height: 30px; width: 30px;\" />\n";
echo "/a></p>\n";
echo "   </footer>\n";
echo "script data-cfasync=\"false\" src=\"/cdn-cgi/scripts/5c5dd728/cloudflare-static/email-decode.min.js\"></script></body>\n";
echo "/html>\n";
?>